name: Check TODO in project

on:
  workflow_call:


jobs:
  check_todo:
    name: Check TODO in project
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.USED_LFS }}
          fetch-depth: 0

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          CLOSE_ISSUES: true
          IDENTIFIERS: '[{"name": "TODO", "labels": ["tech-debt"]}]'